## Create Own Linear Regression Function

**Prediction (the line equation)**
$$\hat{y} = mx + b$$

**Slope**
$$m = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})^2}$$

**Intercept**
$$b = \bar{y} - m\bar{x}$$

### Example 2

In [128]:
import numpy as np
from sklearn.datasets import load_diabetes

In [129]:
class LinearRegression:
    
    def __init__(self):
        self.weights = None   # Coefficients for all features
        self.bias = None      # Intercept term

    def fit(self, X_train, y_train):
        """
        X_train: shape (n_samples, n_features)
        y_train: shape (n_samples,)
        """

        # Convert to numpy arrays
        X_train = np.array(X_train)
        y_train = np.array(y_train)

        n_samples, n_features = X_train.shape

        # Normal Equation:
        # W = (X^T X)^(-1) X^T y

        # Add bias column of 1s
        X_b = np.c_[np.ones((n_samples, 1)), X_train]

        # Compute weights
        theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_train)

        # Separate bias and weights
        self.bias = theta[0]
        self.weights = theta[1:]

        print("Weights:", self.weights)
        print("Bias:", self.bias)

    def predict(self, X_test):
        """
        X_test: shape (n_samples, n_features)
        """
        X_test = np.array(X_test)

        predictions = X_test.dot(self.weights) + self.bias

        return predictions

In [130]:
class LinearRegressionSGD:
    
    def __init__(self, learning_rate=0.01, epochs=1000):
        # Step size for weight updates
        self.learning_rate = learning_rate
        
        # Number of full passes over data
        self.epochs = epochs
        
        # Model parameters
        self.weights = None
        self.bias = None

    def fit(self, X_train, y_train):
        
        # Convert input to NumPy arrays
        X_train = np.array(X_train)
        y_train = np.array(y_train)
        
        # Get number of samples and features
        n_samples, n_features = X_train.shape
        
        # Initialize weights as zeros
        self.weights = np.zeros(n_features)
        
        # Initialize bias
        self.bias = 0
        
        # Training loop
        for epoch in range(self.epochs):
            
            # Loop through each training sample
            for i in range(n_samples):
                
                # Select single sample
                x_i = X_train[i]
                y_i = y_train[i]
                
                # Prediction for current sample
                y_pred = np.dot(x_i, self.weights) + self.bias
                
                # Calculate gradients
                dw = -2 * x_i * (y_i - y_pred)
                db = -2 * (y_i - y_pred)
                
                # Update weights and bias
                self.weights = self.weights - self.learning_rate * dw
                self.bias = self.bias - self.learning_rate * db

            # Optional: print loss every 100 epochs
            if epoch % 100 == 0:
                predictions = np.dot(X_train, self.weights) + self.bias
                loss = np.mean((y_train - predictions) ** 2)
                print(f"Epoch {epoch}: Loss = {loss}")

    def predict(self, X_test):
        
        # Convert to NumPy array
        X_test = np.array(X_test)
        
        # Predict
        return np.dot(X_test, self.weights) + self.bias

In [131]:
X, y = load_diabetes(return_X_y=True)

In [156]:
from sklearn.model_selection import train_test_split

In [157]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [153]:
lr = LinearRegressionSGD()

In [154]:
lr.fit(X_train, y_train)

Epoch 0: Loss = 346.733502788503
Epoch 100: Loss = 114.15333231923351
Epoch 200: Loss = 114.13846026221876
Epoch 300: Loss = 114.12359133968303
Epoch 400: Loss = 114.10872555106803
Epoch 500: Loss = 114.09386289581578
Epoch 600: Loss = 114.07900337336775
Epoch 700: Loss = 114.0641469831666
Epoch 800: Loss = 114.04929372465418
Epoch 900: Loss = 114.03444359727263


In [136]:
y_pred = lr.predict(X_test)

In [137]:
from sklearn.metrics import r2_score

In [138]:
r2_score(y_test, y_pred)

0.44193654410608185

In [139]:
lr.weights

array([  -7.14147957, -204.52302376,  528.83650713,  343.14382517,
       -136.56552807,  -57.88583902, -160.87894833,   63.02832762,
        569.73347327,   54.27483377])

In [140]:
lr.bias

np.float64(155.74821920206173)

### Dry Run

In [141]:
X_train = [
 [8.5, 2, 5],
 [7.8, 1, 3],
 [9.1, 3, 7],
 [7.1, 0, 1],
]

y_train = [12, 8, 15, 20]

X_train = np.array(X_train)
y_train = np.array(y_train)

# X_train, y_train

X_b = np.c_[np.ones((X_train.shape[0], 1)), X_train]

X_b_inverse = np.linalg.inv(X_b.T.dot(X_b))
X_b_inverse

# W = (X^T X)^(-1) X^T y
theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_train)
# theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_train)

theta



array([ -497.        ,   -85.41193088, -2063.        ,  1066.        ])

In [142]:
theta[0]

np.float64(-497.0)

In [143]:
theta[:]

array([ -497.        ,   -85.41193088, -2063.        ,  1066.        ])

In [144]:
# X_train.shape[0]
# np.ones((3,1))
# np.ones((X_train.shape[0], 1))
X_train

array([[8.5, 2. , 5. ],
       [7.8, 1. , 3. ],
       [9.1, 3. , 7. ],
       [7.1, 0. , 1. ]])

In [145]:
X_b

array([[1. , 8.5, 2. , 5. ],
       [1. , 7.8, 1. , 3. ],
       [1. , 9.1, 3. , 7. ],
       [1. , 7.1, 0. , 1. ]])

In [146]:
X_b.T

array([[1. , 1. , 1. , 1. ],
       [8.5, 7.8, 9.1, 7.1],
       [2. , 1. , 3. , 0. ],
       [5. , 3. , 7. , 1. ]])

In [147]:
X_b.T.dot(X_b)

array([[  4.  ,  32.5 ,   6.  ,  16.  ],
       [ 32.5 , 266.31,  52.1 , 136.7 ],
       [  6.  ,  52.1 ,  14.  ,  34.  ],
       [ 16.  , 136.7 ,  34.  ,  84.  ]])

In [148]:
np.linalg.inv(X_b.T.dot(X_b))

array([[-5.62949953e+14,  1.31061979e+03, -1.12589991e+15,
         5.62949953e+14],
       [-7.61042962e-01,  3.33333333e+02,  4.52140547e+03,
        -2.37236894e+03],
       [-1.12589991e+15,  7.14457292e+03, -2.25179981e+15,
         1.12589991e+15],
       [ 5.62949953e+14, -3.68395313e+03,  1.12589991e+15,
        -5.62949953e+14]])

In [149]:
# np.dot(X_b.T.dot(X_b), np.linalg.inv(X_b.T.dot(X_b)))

In [ ]:
np.ones((3, 1))

array([1., 1., 1.])

In [176]:
class LinearRegression:
    def __init__(self):
        self.intercept_ = None
        self.coef_ = None

    def fit(self, X, y):

        X = np.array(X)
        y = np.array(y)

        X_b = np.c_[np.ones((X.shape[0], 1)), X]

        theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

        self.intercept_ =  theta[0]
        self.coef_ =  theta[1:]

    def predict(self, X_test):
        X_test = np.array(X_test)
        return X_test.dot(self.coef_) + self.intercept_

lr = LinearRegression()
lr.fit(X_train, y_train)
lr.predict(X_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16