In [1]:
import torch
import torch.nn as nn

In [26]:
class NNModel(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        # self.linear_1 = nn.Linear(num_features, 3)
        # self.relu = nn.ReLU()
        # self.linear_2 = nn.Linear(3, 1)
        # self.sigmoid = nn.Sigmoid()

        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        # out = self.linear_1(features)
        # out = self.relu(out)
        # out = self.linear_2(out)
        # out = self.sigmoid(out)

        out = self.network(features)

        return out

In [27]:
# create dataset
features = torch.rand(10,5)
features

tensor([[0.9417, 0.3565, 0.5401, 0.4398, 0.5572],
        [0.8253, 0.5811, 0.8744, 0.0165, 0.9994],
        [0.4425, 0.0814, 0.5507, 0.7020, 0.4217],
        [0.4409, 0.3230, 0.2095, 0.4822, 0.4543],
        [0.3030, 0.7944, 0.6038, 0.4542, 0.9784],
        [0.3634, 0.0728, 0.5045, 0.0891, 0.5385],
        [0.5771, 0.1901, 0.3484, 0.3992, 0.8132],
        [0.8686, 0.2801, 0.5242, 0.6042, 0.5388],
        [0.6083, 0.3521, 0.6412, 0.9477, 0.1781],
        [0.0275, 0.1901, 0.7420, 0.6292, 0.9951]])

In [28]:
model = NNModel(features.shape[1])
model.forward(features)

tensor([[0.4268],
        [0.4601],
        [0.4318],
        [0.4217],
        [0.4824],
        [0.4198],
        [0.4291],
        [0.4285],
        [0.4407],
        [0.4760]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear_1.weight

AttributeError: 'NNModel' object has no attribute 'linear_1'

In [22]:
model.linear_1.bias

Parameter containing:
tensor([-0.1257, -0.3232, -0.0636], requires_grad=True)

In [23]:
model.linear_2.weight

Parameter containing:
tensor([[-0.5673, -0.2577, -0.0495]], requires_grad=True)

In [24]:
model.linear_2.bias

Parameter containing:
tensor([-0.3903], requires_grad=True)

In [8]:
!uv pip install torchinfo

Resolved 1 package in 481ms                                          
⠙ Preparing packages... (0/1)                                                   
⠙ Preparing packages... (0/1)-------------------     0 B/22.83 KiB           
⠙ Preparing packages... (0/1)---------- 16.00 KiB/22.83 KiB         
⠙ Preparing packages... (0/1)---------- 22.83 KiB/22.83 KiB         
Prepared 1 package in 23ms                                                        
Installed 1 package in 5ms                                  
 + torchinfo==1.8.0


In [25]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
NNModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00