In [59]:
from sklearn.datasets import make_classification
import torch

In [60]:
X, y = make_classification(
    n_samples=100,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [61]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [62]:
X

tensor([[ 0.5594,  2.3887],
        [ 1.3122, -0.7173],
        [-1.5598, -1.9249],
        [-2.2814, -0.1369],
        [ 1.5607, -0.4280],
        [-0.8080,  1.1966],
        [-0.2706, -2.2555],
        [ 0.4805,  0.5491],
        [-1.2076, -1.2690],
        [ 0.2542, -1.7953],
        [ 2.5912,  0.2447],
        [ 0.0712,  0.4943],
        [-1.1776, -1.2059],
        [ 0.9334,  0.6881],
        [ 1.6521, -0.3589],
        [-1.4074, -1.5683],
        [ 1.0226, -1.0832],
        [-0.8168, -0.6796],
        [ 1.5058, -0.3892],
        [-2.1711, -0.0486],
        [ 0.7148, -1.4292],
        [-0.1501, -0.1171],
        [-1.4118, -1.5333],
        [-2.5859, -0.4093],
        [ 0.8260, -1.0538],
        [-0.0713,  0.0890],
        [ 0.6274, -1.3293],
        [ 1.6588, -0.4313],
        [ 1.2799,  1.2590],
        [ 0.2506,  0.1398],
        [-0.0532,  1.8561],
        [-2.0583, -2.5234],
        [-2.0263,  0.0619],
        [-1.6583, -1.5713],
        [ 1.2801,  1.2894],
        [ 0.9642,  0

In [63]:
y

tensor([0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 0])

In [64]:
from torch.utils.data import Dataset, DataLoader

In [65]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [66]:
dataset = CustomDataset(X, y)

In [67]:
dataset.__len__()

100

In [68]:
dataset.__getitem__(1)

(tensor([ 1.3122, -0.7173]), tensor(1))

In [76]:
dataloader = DataLoader(dataset, batch_size=10, shuffle=False)

In [79]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 0.5594,  2.3887],
        [ 1.3122, -0.7173],
        [-1.5598, -1.9249],
        [-2.2814, -0.1369],
        [ 1.5607, -0.4280],
        [-0.8080,  1.1966],
        [-0.2706, -2.2555],
        [ 0.4805,  0.5491],
        [-1.2076, -1.2690],
        [ 0.2542, -1.7953]])
tensor([0, 1, 0, 0, 1, 0, 1, 1, 0, 1])
--------------------------------------------------
tensor([[ 2.5912,  0.2447],
        [ 0.0712,  0.4943],
        [-1.1776, -1.2059],
        [ 0.9334,  0.6881],
        [ 1.6521, -0.3589],
        [-1.4074, -1.5683],
        [ 1.0226, -1.0832],
        [-0.8168, -0.6796],
        [ 1.5058, -0.3892],
        [-2.1711, -0.0486]])
tensor([1, 0, 0, 1, 1, 0, 1, 0, 1, 0])
--------------------------------------------------
tensor([[ 0.7148, -1.4292],
        [-0.1501, -0.1171],
        [-1.4118, -1.5333],
        [-2.5859, -0.4093],
        [ 0.8260, -1.0538],
        [-0.0713,  0.0890],
        [ 0.6274, -1.3293],
        [ 1.6588, -0.4313],
        [ 1.2799,  1.2590],
      